
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diki Hamdani
 */
public class FormPenjualanDikiHamdani extends javax.swing.JFrame {

    /**
     * Creates new form FormPenjualanDikiHamdani
     */
    String data[][];
    String col[] = {"Kode Barang", "Nama Barang", "Harga", "Jumlah Beli", "Jumlah bayar", "Diskon", "Total"};
    DefaultTableModel model = new DefaultTableModel(data, col);
    
    public void hitungJumlahBayar() {
        Double harga, jml;
        harga = Double.parseDouble(harga_dikihamdani.getText());
        jml = Double.parseDouble(jumlah_beli_dikihamdani.getText());
        
        jumlah_bayar_dikihamdani.setText("" + (int)(harga * jml));
    }
    
    public void hitungDiskon() {
        Double jml, diskon;
        jml = Double.parseDouble(jumlah_bayar_dikihamdani.getText());
        diskon = 0.1;
        if (jml >= 300000) {
            diskon_dikihamdani.setText("" + (int)(jml * diskon));
        } else {
            diskon_dikihamdani.setText("" + 0);
        }
    }
    
    public void hitungTotal() {
        Double jml, diskon;
        jml = Double.parseDouble(jumlah_bayar_dikihamdani.getText());
        diskon = Double.parseDouble(diskon_dikihamdani.getText());

        total_dikihamdani.setText("" + (int)(jml - diskon));
    }
    
    public void selectItem() {
        if (kode_barang_dikihamdani.getSelectedItem() == "BRG001") {
            nama_barang_dikihamdani.setText("Sleeping Bag");
            harga_dikihamdani.setText("" + 120000);
        }
        else if (kode_barang_dikihamdani.getSelectedItem() == "BRG002") {
            nama_barang_dikihamdani.setText("Sepatu Gunung");
            harga_dikihamdani.setText("" + 320000);
        }
        else if (kode_barang_dikihamdani.getSelectedItem() == "BRG003") {
            nama_barang_dikihamdani.setText("Tenda Camping");
            harga_dikihamdani.setText("" + 450000);
        }
        else if (kode_barang_dikihamdani.getSelectedItem() == "BRG004") {
            nama_barang_dikihamdani.setText("Kompor Portabel");
            harga_dikihamdani.setText("" + 150000);
        }
        else if (kode_barang_dikihamdani.getSelectedItem() == "BRG005") {
            nama_barang_dikihamdani.setText("Jaket Tebal");
            harga_dikihamdani.setText("" + 150000);
        }
    }
    
    public void clean() {
        kode_barang_dikihamdani.setSelectedIndex(0);
        nama_barang_dikihamdani.setText("");
        harga_dikihamdani.setText("");
        jumlah_beli_dikihamdani.setText("");
        jumlah_bayar_dikihamdani.setText("");
        diskon_dikihamdani.setText("");
        total_dikihamdani.setText("");
    }
    
    public void cleanTable() {
        DefaultTableModel tableModel = (DefaultTableModel)tabel_dikihamdani.getModel();
        while (tableModel.getRowCount() > 0) {
            tableModel.removeRow(0);
        }
    }    
  
    public FormPenjualanDikiHamdani() {
        initComponents();
        // autimatically centered window on the screen
        setLocationRelativeTo(null);
        
        // set focus
        kode_barang_dikihamdani.requestFocus();
        
        // disable mutable text field
        nama_barang_dikihamdani.setEditable(false);
        harga_dikihamdani.setEditable(false);
        diskon_dikihamdani.setEditable(false);
        total_dikihamdani.setEditable(false);
        jumlah_bayar_dikihamdani.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        harga_dikihamdani = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jumlah_beli_dikihamdani = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jumlah_bayar_dikihamdani = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        diskon_dikihamdani = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        total_dikihamdani = new javax.swing.JTextField();
        kode_barang_dikihamdani = new javax.swing.JComboBox<>();
        nama_barang_dikihamdani = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_dikihamdani = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btn_tambah_dikihamdani = new javax.swing.JButton();
        btn_hapus_dikihamdani = new javax.swing.JButton();
        btn_simpan_dikihamdani = new javax.swing.JButton();
        btn_bersihkan_dikihamdani = new javax.swing.JButton();
        btn_keluar_dikihamdani = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APLIKASI PENJUALAN");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM PENJUALAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Kode Barang");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nama Barang");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Harga");

        harga_dikihamdani.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        harga_dikihamdani.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                harga_dikihamdaniFocusGained(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Jumlah Beli");

        jumlah_beli_dikihamdani.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jumlah_beli_dikihamdani.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jumlah_beli_dikihamdaniKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Jumlah Bayar");

        jumlah_bayar_dikihamdani.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jumlah_bayar_dikihamdani.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jumlah_bayar_dikihamdaniFocusGained(evt);
            }
        });
        jumlah_bayar_dikihamdani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah_bayar_dikihamdaniActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Diskon");

        diskon_dikihamdani.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        diskon_dikihamdani.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                diskon_dikihamdaniFocusGained(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Total Bayar");

        total_dikihamdani.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total_dikihamdani.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                total_dikihamdaniFocusGained(evt);
            }
        });

        kode_barang_dikihamdani.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kode_barang_dikihamdani.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Kode Barang --", "BRG001", "BRG002", "BRG003", "BRG004", "BRG005" }));
        kode_barang_dikihamdani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_barang_dikihamdaniActionPerformed(evt);
            }
        });
        kode_barang_dikihamdani.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kode_barang_dikihamdaniKeyTyped(evt);
            }
        });

        nama_barang_dikihamdani.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nama_barang_dikihamdani.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nama_barang_dikihamdaniFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(117, 117, 117)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(harga_dikihamdani)
                    .addComponent(jumlah_beli_dikihamdani)
                    .addComponent(jumlah_bayar_dikihamdani)
                    .addComponent(diskon_dikihamdani)
                    .addComponent(total_dikihamdani)
                    .addComponent(kode_barang_dikihamdani, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nama_barang_dikihamdani))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(kode_barang_dikihamdani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nama_barang_dikihamdani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(harga_dikihamdani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jumlah_beli_dikihamdani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jumlah_bayar_dikihamdani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(diskon_dikihamdani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(total_dikihamdani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabel_dikihamdani.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabel_dikihamdani);

        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        btn_tambah_dikihamdani.setText("Tambah");
        btn_tambah_dikihamdani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_dikihamdaniActionPerformed(evt);
            }
        });

        btn_hapus_dikihamdani.setText("Hapus");
        btn_hapus_dikihamdani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus_dikihamdaniActionPerformed(evt);
            }
        });

        btn_simpan_dikihamdani.setText("Simpan");
        btn_simpan_dikihamdani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpan_dikihamdaniActionPerformed(evt);
            }
        });

        btn_bersihkan_dikihamdani.setText("Bersihkan");
        btn_bersihkan_dikihamdani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bersihkan_dikihamdaniActionPerformed(evt);
            }
        });

        btn_keluar_dikihamdani.setText("Keluar");
        btn_keluar_dikihamdani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluar_dikihamdaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_keluar_dikihamdani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btn_tambah_dikihamdani, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btn_hapus_dikihamdani, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btn_simpan_dikihamdani, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(btn_bersihkan_dikihamdani, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_simpan_dikihamdani, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tambah_dikihamdani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_bersihkan_dikihamdani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_hapus_dikihamdani, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_keluar_dikihamdani, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambah_dikihamdaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_dikihamdaniActionPerformed
        tabel_dikihamdani.setModel(model);
        model.insertRow(tabel_dikihamdani.getRowCount(), new Object[] {
            kode_barang_dikihamdani.getSelectedItem().toString(),
            nama_barang_dikihamdani.getText(),
            harga_dikihamdani.getText(),
            jumlah_beli_dikihamdani.getText(),
            jumlah_bayar_dikihamdani.getText(),
            diskon_dikihamdani.getText(),
            total_dikihamdani.getText()
        });
        clean();
    }//GEN-LAST:event_btn_tambah_dikihamdaniActionPerformed

    private void btn_bersihkan_dikihamdaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bersihkan_dikihamdaniActionPerformed
        // TODO add your handling code here:
        clean();
    }//GEN-LAST:event_btn_bersihkan_dikihamdaniActionPerformed

    private void btn_keluar_dikihamdaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluar_dikihamdaniActionPerformed
        int Reply = JOptionPane.showConfirmDialog(null,
                "Apakah kamu yakin akan keluar?",
                "Konfrimasi",
                JOptionPane.YES_NO_OPTION);
        
        if (Reply == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_keluar_dikihamdaniActionPerformed

    private void jumlah_bayar_dikihamdaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_bayar_dikihamdaniActionPerformed
        // TODO add your handling code here:
        hitungJumlahBayar();
    }//GEN-LAST:event_jumlah_bayar_dikihamdaniActionPerformed

    private void jumlah_bayar_dikihamdaniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jumlah_bayar_dikihamdaniFocusGained
        // TODO add your handling code here:
        hitungJumlahBayar();
        diskon_dikihamdani.requestFocus();
    }//GEN-LAST:event_jumlah_bayar_dikihamdaniFocusGained

    private void harga_dikihamdaniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_harga_dikihamdaniFocusGained
        // TODO add your handling code here:
        jumlah_beli_dikihamdani.requestFocus();
    }//GEN-LAST:event_harga_dikihamdaniFocusGained

    private void total_dikihamdaniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_total_dikihamdaniFocusGained
        // TODO add your handling code here:
        hitungTotal();
    }//GEN-LAST:event_total_dikihamdaniFocusGained

    private void diskon_dikihamdaniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_diskon_dikihamdaniFocusGained
        // TODO add your handling code here:
        hitungDiskon();
        total_dikihamdani.requestFocus();
    }//GEN-LAST:event_diskon_dikihamdaniFocusGained

    private void btn_simpan_dikihamdaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpan_dikihamdaniActionPerformed
        try {
            String hasil = "";
            for (int i=0; i<tabel_dikihamdani.getRowCount(); i++) {
                for (int j=0; j<tabel_dikihamdani.getColumnCount(); j++) {
                    hasil += tabel_dikihamdani.getModel().getValueAt(i, j) + ";";
                }
                hasil += "\r\n";
            }
            BufferedWriter out = new BufferedWriter(new FileWriter("database.txt", true));
            out.write(hasil);
            JOptionPane.showMessageDialog(null, "Berhasil disimpan");
            out.close();
        } catch (Exception e) {
            System.err.println("Terjadi kesalahan: " + e);
        }
        cleanTable();
    }//GEN-LAST:event_btn_simpan_dikihamdaniActionPerformed

    private void jumlah_beli_dikihamdaniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlah_beli_dikihamdaniKeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jumlah_bayar_dikihamdani.requestFocus();
        }
    }//GEN-LAST:event_jumlah_beli_dikihamdaniKeyTyped

    private void kode_barang_dikihamdaniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kode_barang_dikihamdaniKeyTyped
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jumlah_beli_dikihamdani.requestFocus();
        }
    }//GEN-LAST:event_kode_barang_dikihamdaniKeyTyped

    private void nama_barang_dikihamdaniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nama_barang_dikihamdaniFocusGained
//        selectItem();
    }//GEN-LAST:event_nama_barang_dikihamdaniFocusGained

    private void btn_hapus_dikihamdaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus_dikihamdaniActionPerformed
        model.removeRow(tabel_dikihamdani.getSelectedRow());
    }//GEN-LAST:event_btn_hapus_dikihamdaniActionPerformed

    private void kode_barang_dikihamdaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_barang_dikihamdaniActionPerformed
        // TODO add your handling code here:
        selectItem();
    }//GEN-LAST:event_kode_barang_dikihamdaniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPenjualanDikiHamdani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPenjualanDikiHamdani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPenjualanDikiHamdani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPenjualanDikiHamdani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPenjualanDikiHamdani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bersihkan_dikihamdani;
    private javax.swing.JButton btn_hapus_dikihamdani;
    private javax.swing.JButton btn_keluar_dikihamdani;
    private javax.swing.JButton btn_simpan_dikihamdani;
    private javax.swing.JButton btn_tambah_dikihamdani;
    private javax.swing.JTextField diskon_dikihamdani;
    private javax.swing.JTextField harga_dikihamdani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlah_bayar_dikihamdani;
    private javax.swing.JTextField jumlah_beli_dikihamdani;
    private javax.swing.JComboBox<String> kode_barang_dikihamdani;
    private javax.swing.JTextField nama_barang_dikihamdani;
    private javax.swing.JTable tabel_dikihamdani;
    private javax.swing.JTextField total_dikihamdani;
    // End of variables declaration//GEN-END:variables
}
